language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:setup
#- bundle exec rake db:test:prepare
env:
  global:
  - secure: G1oS+ZXo5Ogrj0vsUd/UG2mZ5anPr7oELeTYRML42UdtE34aCuLwiWCOgMkCWZpcp9OIgPzHOG8IEfqrFJUQbA7oTYHib4C2WQTkz18hyqcvsMnHTv2WBIrW0RIMrPhx3gsYiXE3f5eYJAxWGqj9L9LFa7XBToBxRRISA/fZiys=
script:
- bundle exec rspec
#- bundle exec rubocop